services:
  postgres:
    image: postgres:16-alpine
    container_name: pg2hydra-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - '5432:5432'
    volumes:
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/01-seed.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d appdb']
      interval: 3s
      timeout: 3s
      retries: 20
